/** \file
 *  This C header file was generated by $ANTLR version 3.4
 *
 *     -  From the grammar source file : ./StreamSQL.g
 *     -                            On : 2023-02-15 17:42:06
 *     -                for the parser : StreamSQLParserParser
 *
 * Editing it, at least manually, is not wise.
 *
 * C language generator and runtime by Jim Idle, jimi|hereisanat|idle|dotgoeshere|ws.
 *
 *
 * The parser 
StreamSQLParser

has the callable functions (rules) shown below,
 * which will invoke the code for the associated rule in the source grammar
 * assuming that the input stream is pointing to a token/text stream that could begin
 * this rule.
 *
 * For instance if you call the first (topmost) rule in a parser grammar, you will
 * get the results of a full parse, but calling a rule half way through the grammar will
 * allow you to pass part of a full token stream to the parser, such as for syntax checking
 * in editors and so on.
 *
 * The parser entry points are called indirectly (by function pointer to function) via
 * a parser context typedef pStreamSQLParser, which is returned from a call to StreamSQLParserNew().
 *
 * The methods in pStreamSQLParser are  as follows:
 *
 *  - 
 StreamSQLParser_statement_return
      pStreamSQLParser->statement(pStreamSQLParser)
 *  - 
 StreamSQLParser_selectStatement_return
      pStreamSQLParser->selectStatement(pStreamSQLParser)
 *  - 
 StreamSQLParser_selectList_return
      pStreamSQLParser->selectList(pStreamSQLParser)
 *  - 
 StreamSQLParser_selectColumn_return
      pStreamSQLParser->selectColumn(pStreamSQLParser)
 *  - 
 StreamSQLParser_selectItem_return
      pStreamSQLParser->selectItem(pStreamSQLParser)
 *  - 
 StreamSQLParser_selectExpression_return
      pStreamSQLParser->selectExpression(pStreamSQLParser)
 *  - 
 StreamSQLParser_createStatement_return
      pStreamSQLParser->createStatement(pStreamSQLParser)
 *  - 
 StreamSQLParser_schemaList_return
      pStreamSQLParser->schemaList(pStreamSQLParser)
 *  - 
 StreamSQLParser_streamType_return
      pStreamSQLParser->streamType(pStreamSQLParser)
 *  - 
 StreamSQLParser_columnNameType_return
      pStreamSQLParser->columnNameType(pStreamSQLParser)
 *  - 
 StreamSQLParser_dataType_return
      pStreamSQLParser->dataType(pStreamSQLParser)
 *
 * The return type for any particular rule is of course determined by the source
 * grammar file.
 */
// [The "BSD license"]
// Copyright (c) 2005-2009 Jim Idle, Temporal Wave LLC
// http://www.temporal-wave.com
// http://www.linkedin.com/in/jimidle
//
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
// 3. The name of the author may not be used to endorse or promote products
//    derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

#ifndef	_StreamSQLParser_H
#define _StreamSQLParser_H
/* =============================================================================
 * Standard antlr3 C runtime definitions
 */
#include    <antlr3.h>

/* End of standard antlr 3 runtime definitions
 * =============================================================================
 */

#ifdef __cplusplus
extern "C" {
#endif

// Forward declare the context typedef so that we can use it before it is
// properly defined. Delegators and delegates (from import statements) are
// interdependent and their context structures contain pointers to each other
// C only allows such things to be declared if you pre-declare the typedef.
//
typedef struct StreamSQLParser_Ctx_struct StreamSQLParser, * pStreamSQLParser;



#ifdef	ANTLR3_WINDOWS
// Disable: Unreferenced parameter,							- Rules with parameters that are not used
//          constant conditional,							- ANTLR realizes that a prediction is always true (synpred usually)
//          initialized but unused variable					- tree rewrite variables declared but not needed
//          Unreferenced local variable						- lexer rule declares but does not always use _type
//          potentially unitialized variable used			- retval always returned from a rule
//			unreferenced local function has been removed	- susually getTokenNames or freeScope, they can go without warnigns
//
// These are only really displayed at warning level /W4 but that is the code ideal I am aiming at
// and the codegen must generate some of these warnings by necessity, apart from 4100, which is
// usually generated when a parser rule is given a parameter that it does not use. Mostly though
// this is a matter of orthogonality hence I disable that one.
//
#pragma warning( disable : 4100 )
#pragma warning( disable : 4101 )
#pragma warning( disable : 4127 )
#pragma warning( disable : 4189 )
#pragma warning( disable : 4505 )
#pragma warning( disable : 4701 )
#endif
typedef struct StreamSQLParser_statement_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    StreamSQLParser_statement_return;



typedef struct StreamSQLParser_selectStatement_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    StreamSQLParser_selectStatement_return;



typedef struct StreamSQLParser_selectList_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    StreamSQLParser_selectList_return;



typedef struct StreamSQLParser_selectColumn_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    StreamSQLParser_selectColumn_return;



typedef struct StreamSQLParser_selectItem_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    StreamSQLParser_selectItem_return;



typedef struct StreamSQLParser_selectExpression_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    StreamSQLParser_selectExpression_return;



typedef struct StreamSQLParser_createStatement_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    StreamSQLParser_createStatement_return;



typedef struct StreamSQLParser_schemaList_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    StreamSQLParser_schemaList_return;



typedef struct StreamSQLParser_streamType_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    StreamSQLParser_streamType_return;



typedef struct StreamSQLParser_columnNameType_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    StreamSQLParser_columnNameType_return;



typedef struct StreamSQLParser_dataType_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    StreamSQLParser_dataType_return;




/** Context tracking structure for 
StreamSQLParser

 */
struct StreamSQLParser_Ctx_struct
{
    /** Built in ANTLR3 context tracker contains all the generic elements
     *  required for context tracking.
     */
    pANTLR3_PARSER   pParser;

     StreamSQLParser_statement_return
     (*statement)	(struct StreamSQLParser_Ctx_struct * ctx);

     StreamSQLParser_selectStatement_return
     (*selectStatement)	(struct StreamSQLParser_Ctx_struct * ctx);

     StreamSQLParser_selectList_return
     (*selectList)	(struct StreamSQLParser_Ctx_struct * ctx);

     StreamSQLParser_selectColumn_return
     (*selectColumn)	(struct StreamSQLParser_Ctx_struct * ctx);

     StreamSQLParser_selectItem_return
     (*selectItem)	(struct StreamSQLParser_Ctx_struct * ctx);

     StreamSQLParser_selectExpression_return
     (*selectExpression)	(struct StreamSQLParser_Ctx_struct * ctx);

     StreamSQLParser_createStatement_return
     (*createStatement)	(struct StreamSQLParser_Ctx_struct * ctx);

     StreamSQLParser_schemaList_return
     (*schemaList)	(struct StreamSQLParser_Ctx_struct * ctx);

     StreamSQLParser_streamType_return
     (*streamType)	(struct StreamSQLParser_Ctx_struct * ctx);

     StreamSQLParser_columnNameType_return
     (*columnNameType)	(struct StreamSQLParser_Ctx_struct * ctx);

     StreamSQLParser_dataType_return
     (*dataType)	(struct StreamSQLParser_Ctx_struct * ctx);
    // Delegated rules

    const char * (*getGrammarFileName)();
    void            (*reset)  (struct StreamSQLParser_Ctx_struct * ctx);
    void	    (*free)   (struct StreamSQLParser_Ctx_struct * ctx);
/* @headerFile.members() */
pANTLR3_BASE_TREE_ADAPTOR	adaptor;
pANTLR3_VECTOR_FACTORY		vectors;
/* End @headerFile.members() */
};

// Function protoypes for the constructor functions that external translation units
// such as delegators and delegates may wish to call.
//
ANTLR3_API pStreamSQLParser StreamSQLParserNew         (
pANTLR3_COMMON_TOKEN_STREAM
 instream);
ANTLR3_API pStreamSQLParser StreamSQLParserNewSSD      (
pANTLR3_COMMON_TOKEN_STREAM
 instream, pANTLR3_RECOGNIZER_SHARED_STATE state);

/** Symbolic definitions of all the tokens that the 
parser
 will work with.
 * \{
 *
 * Antlr will define EOF, but we can't use that as it it is too common in
 * in C header files and that would be confusing. There is no way to filter this out at the moment
 * so we just undef it here for now. That isn't the value we get back from C recognizers
 * anyway. We are looking for ANTLR3_TOKEN_EOF.
 */
#ifdef	EOF
#undef	EOF
#endif
#ifdef	Tokens
#undef	Tokens
#endif
#define EOF      -1
#define COMMA      4
#define DOT      5
#define Digit      6
#define Exponent      7
#define Identifier      8
#define KW_ADVANCE      9
#define KW_AS      10
#define KW_CREATE      11
#define KW_DOUBLE      12
#define KW_FROM      13
#define KW_INPUT      14
#define KW_INT      15
#define KW_INTO      16
#define KW_ON      17
#define KW_OUTPUT      18
#define KW_SCHEMA      19
#define KW_SELECT      20
#define KW_SIZE      21
#define KW_STREAM      22
#define KW_WINDOW      23
#define LPAREN      24
#define LSQUARE      25
#define Letter      26
#define MINUS      27
#define Number      28
#define PLUS      29
#define RPAREN      30
#define RSQUARE      31
#define SEMICOLON      32
#define TOK_CREATE_SCHEMA      33
#define TOK_CREATE_STREAM      34
#define TOK_CREATE_WINDOW      35
#define TOK_NAME_TYPE      36
#define TOK_SCHEMA_LIST      37
#define TOK_SELECT      38
#define TOK_SELEXPR      39
#define TOK_SELITEM      40
#define TOK_SELLIST      41
#define WS      42
#ifdef	EOF
#undef	EOF
#define	EOF	ANTLR3_TOKEN_EOF
#endif

#ifndef TOKENSOURCE
#define TOKENSOURCE(lxr) lxr->pLexer->rec->state->tokSource
#endif

/* End of token definitions for StreamSQLParser
 * =============================================================================
 */
/** } */

#ifdef __cplusplus
}
#endif

#endif

/* END - Note:Keep extra line feed to satisfy UNIX systems */
